ImgDirectory: "/home/dtrishkin/Desktop/new_diplom_work/mini_neuronet_py/mem_0.1"
MemDirectory: "/home/dtrishkin/Desktop/new_diplom_work/mini_neuronet_py/mem_0.4"
# ImgDirectory: "/home/s-quark/Desktop/new_diplom_work/mini_neuronet_py/mem_0.1"