# ImgDirectory: "/home/dtrishkin/Desktop/new_diplom_work/mini_neuronet_py/mem_0.1"
# MemDirectory: "/home/dtrishkin/Desktop/new_diplom_work/mini_neuronet_py/mem_0.5"
ImgDirectory: "/home/s-quark/Desktop/new_diplom_work/mini_neuronet_py/mem_1.0"
MemDirectory: "/home/s-quark/Desktop/new_diplom_work/mini_neuronet_py/mem_1.1"